name: Run Playwright Tests
on:
  workflow_call:
    inputs:
      site_id:
        required: true
        type: string
      site_name:
        required: true
        type: string
      type:
        required: true
        type: string
      site_url:
        required: true
        type: string
      os:
        required: false
        type: string
      ssh_key:
        required: true
        type: string
      terminus_token:
        required: true
        type: string
      github_token:
        required: true
        type: string
      pr:
        required: false
        type: string
      workspace:
        required: true
        type: string

runs:
  using: composite
  steps:
    - name: Set colors
      shell: bash
      run: |
        echo "RED=\033[1;31m" >> $GITHUB_ENV
        echo "GREEN=\033[1;32m" >> $GITHUB_ENV
        echo "BLUE=\033[1;34m" >> $GITHUB_ENV
        echo "YELLOW=\033[1;33m" >> $GITHUB_ENV
        echo "RESET=\033[0m" >> $GITHUB_ENV

    - name: Set Upstream
      shell: bash
      run: |
        UPSTREAM_ID="90a683cd-4e03-4832-9b49-be97ab2a0be4"
        if [ ${{ inputs.type }} != 'single' ]; then
          UPSTREAM_ID="c784d2e5-2715-47a1-b163-123bba915b9b"
        fi
        echo "UPSTREAM_ID=${UPSTREAM_ID}" >> $GITHUB_ENV

    - name: Generate lock files
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Generate lock files${{ env.RESET }}"
        npm install --package-lock-only

    - name: Set up cache for dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.composer/cache
          ./vendor
          ~/.npm
          ./node_modules
        key: ${{ inputs.os }}-deps-${{ hashFiles( '**/composer.json', '**/package-lock.json' ) }}
        restore-keys: ${{ inputs.os }}-deps-

    - name: Install Composer dependencies
      if: steps.cache.outputs.cache-hit != true
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Install Composer dependencies${{ env.RESET }}"
        stdbuf -oL -eL composer update --no-progress --prefer-dist --optimize-autoloader

    - name: Install NPM dependencies
      if: steps.cache.outputs.cache-hit != true
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Install NPM dependencies${{ env.RESET }}"
        stdbuf -oL -eL npm ci

    - name: Install Playwright Browsers
      shell: bash
      run: |
        echo -e "${{ env.YELLOW }}Install Playwright Browsers${{ env.RESET }}"
        stdbuf -oL -eL npx playwright install --with-deps

    - name: Install SSH keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_key }}

    - name: Get latest Terminus release
      uses: pantheon-systems/terminus-github-actions@v1
      with:
        pantheon-machine-token: ${{ inputs.terminus_token }}

    - name: Validate Pantheon Host Key
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Validate Pantheon Host Key${{ env.RESET }}"
        echo "Host *.drush.in HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
        echo "Host *.drush.in PubkeyAcceptedKeyTypes +ssh-rsa" >> ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Log into Terminus
      shell: bash
      run: |
        echo -e "${{ env.YELLOW }}Log into Terminus${{ env.RESET }}"
        terminus auth:login --machine-token=${{ inputs.terminus_token }}

    - name: Display art
      shell: bash
      run: terminus art wordpress

    - name: Create Site
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Create ${{ inputs.site_id }} if it does not exist.${{ env.RESET }}"
        if terminus site:info ${{ inputs.site_id }}; then
          echo "Test site already exists, skipping site creation."
          # If the site exists already, we should switch it to git mode.
          stdbuf -oL -eL terminus connection:set ${{ inputs.site_id }}.dev git -y
        else
        stdbuf -oL -eL terminus site:create ${{ inputs.site_id }} "${{ inputs.site_name }}" ${{ env.UPSTREAM_ID }} --org=5ae1fa30-8cc4-4894-8ca9-d50628dcba17
        fi

    - name: Clone the site locally and copy PR updates
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Clone the site locally and copy PR updates${{ env.RESET }}"
        echo "Setting up some git config..."
        git config --global user.email "cms-platform+sage-testing@pantheon.io"
        git config --global user.name "Pantheon WPCM Bot"
        PR_NUMBER=$(echo ${{ inputs.pr }})
        echo "Pull Request Number: ${PR_NUMBER}"
        COMMIT_MSG=$(gh pr view ${PR_NUMBER} --json commits --jq '.commits[-1] | "\(.messageHeadline) \(.messageBody)"')
        echo "Commit Message: ${COMMIT_MSG}"
        echo -e "${{ env.YELLOW }}Cloning the site${{ env.RESET }}"
        stdbuf -oL -eL terminus local:clone ${{ inputs.site_id }}
        cd ~/pantheon-local-copies/${{ inputs.site_id }}
        echo -e "${{ env.YELLOW }}Copying latest changes and committing to the site.${{ env.RESET }}"
        rsync -a --exclude='.git' ${{ inputs.workspace }}/ .
        git add -A
        stdbuf -oL -eL git commit -m "Update to latest commit: ${COMMIT_MSG}" || true
        stdbuf -oL -eL git push origin master || true

    - name: Copy multisite config file
      if: ${{ inputs.type != 'single' }}
      shell: bash
      run: |
        stdbuf -oL -eL terminus workflow:wait ${{ inputs.site_id }}.dev
        echo ""
        echo -e "${{ env.YELLOW }}Copying multisite application.php${{ env.RESET }}"
        rm ${{ inputs.workspace }}/config/application.php
        cp ${{ inputs.workspace }}/.github/fixtures/config/application.${{ inputs.type }}.php ~/pantheon-local-copies/${{ inputs.site_id }}/config/
        mv ~/pantheon-local-copies/${{ inputs.site_id }}/config/application.${{ inputs.type }}.php ~/pantheon-local-copies/${{ inputs.site_id }}/config/application.php
        cd ~/pantheon-local-copies/${{ inputs.site_id }}
        git add ~/pantheon-local-copies/${{ inputs.site_id }}/config/application.php
        git commit -m "Set up ${{ inputs.type }} multisite config"
        stdbuf -oL -eL git push origin master || true
        stdbuf -oL -eL terminus workflow:wait ${{ inputs.site_id }}.dev

    - name: Status Check
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Checking WordPress install status${{ env.RESET }}"
        stdbuf -oL -eL terminus wp ${{ inputs.site_id }}.dev -- cli info
        if [ ${{ inputs.type }} != 'single' ]; then
          terminus wp ${{ inputs.site_id }}.dev -- config get MULTISITE # Should be true.
          if [ $? -ne 0 ]; then
            echo -e "${{ env.RED }}Multisite not found!"
            exit 1
          fi

          SUBDOMAIN_INSTALL=$(terminus wp ${{ inputs.site_id }}.dev -- config get SUBDOMAIN_INSTALL)
          if [ ${{ inputs.type }} == 'subdir' ]; then
            # SUBDOMAIN_INSTALL should be false.
            if [ $SUBDOMAIN_INSTALL != 0 ]; then
              echo -e "${{ env.RED }}Subdirectory configuration not found!"
              exit 1
            fi
          fi
          if [ ${{ inputs.type }} == 'subdom' ]; then
            # SUBDOMAIN_INSTALL should be true.
            if [ $SUBDOMAIN_INSTALL != 1 ]; then
              echo -e "${{ env.RED }}Subdomain configuration not found!"
              exit 1
            fi
          fi
        fi

    - name: Install (Single Site) WordPress
      if: ${{ inputs.type == 'single' }}
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Install (Single Site) WordPress${{ env.RESET }}"
        terminus wp ${{ inputs.site_id }}.dev -- db reset
        stdbuf -oL -eL terminus wp ${{ inputs.site_id }}.dev -- core install --title="${{ inputs.site_name }}" --admin_user=wpcm --admin_email=test@dev.null
        terminus wp ${{ inputs.site_id }}.dev -- option update permalink_structure '/%postname%/'
        terminus wp ${{ inputs.site_id }}.dev -- rewrite flush
        terminus wp ${{ inputs.site_id }}.dev -- cache flush

    # todo: create fixture site for subdomain multisite tests
    - name: Install (Subdirectory Multisite) WordPress
      if: ${{ inputs.type == 'subdir' }}
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Install (Subdirectory Multisite) WordPress${{ env.RESET }}"
        terminus wp ${{ inputs.site_id }}.dev -- db reset
        stdbuf -oL -eL terminus wp ${{ inputs.site_id }}.dev -- core multisite-install --title="${{ inputs.site_name }}" --admin_user=wpcm --admin_email=test@dev.null --subdomains=false
        terminus wp ${{ inputs.site_id }}.dev -- option update permalink_structure '/%postname%/'
        terminus wp ${{ inputs.site_id }}.dev -- rewrite flush
        terminus wp ${{ inputs.site_id }}.dev -- cache flush

    - name: Install (Subdomain Multisite) WordPress
      if: ${{ inputs.type == 'subdom' }}
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Install (Subdomain Multisite) WordPress${{ env.RESET }}"
        terminus wp ${{ inputs.site_id }}.dev -- db reset
        stdbuf -oL -eL terminus wp ${{ inputs.site_id }}.dev -- core multisite-install --title="${{ inputs.site_name }}" --admin_user=wpcm --admin_email=test@dev.null --subdomains=true
        terminus wp ${{ inputs.site_id }}.dev -- option update permalink_structure '/%postname%/'
        terminus wp ${{ inputs.site_id }}.dev -- rewrite flush
        terminus wp ${{ inputs.site_id }}.dev -- cache flush

    - name: Set up subsite
      if: ${{ inputs.type == 'subdom' || inputs.type == 'subdir' }}
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.YELLOW }}Set up subsite${{ env.RESET }}"
        # Set a URL var for the type of multisite.
        if [ "${{ inputs.type }}" == 'subdom' ]; then
          URL="foo.dev-${{ inputs.site_id }}.pantheonsite.io"
        fi
        if [ "${{ inputs.type }}" == 'subdir' ]; then
          URL="${{ inputs.site_url }}/foo"
        fi

        # Check if the sub-site already exists.
        EXISTING_SITE=$(terminus wp ${{ inputs.site_id }}.dev -- site list --field=url | grep -w "$URL")

        if [ -z "$EXISTING_SITE" ]; then
          # Create the sub-site only if it does not already exist.
          stdbuf -oL -eL terminus wp ${{ inputs.site_id }}.dev -- site create --slug=foo --title="Foo" --email="foo@dev.null"
          terminus wp ${{ inputs.site_id }}.dev -- option update permalink_structure '/%postname%/' --url="$URL"
        else
          echo -e "${{ env.YELLOW }}Sub-site already exists at $URL. Skipping creation.${{ env.RESET }}"
        fi
        terminus wp ${{ inputs.site_id }}.dev -- option update permalink_structure '/%postname%/' --url="$URL"

    - name: Install WP GraphQL
      shell: bash
      run: |
        stdbuf -oL -eL terminus workflow:wait ${{ inputs.site_id }}.dev --max=10
        terminus connection:set ${{ inputs.site_id }}.dev sftp
        echo ""
        echo -e "${{ env.YELLOW }}Install WP GraphQL${{ env.RESET }}"
        terminus wp ${{ inputs.site_id }}.dev -- plugin install --activate wp-graphql
        if [ "${{ inputs.type }}" == 'subdom' ]; then
          # We're going to assume the foo.dev subdomain already exists.
          stdbuf -oL -eL terminus wp ${{ inputs.site_id }}.dev -- plugin activate wp-graphql --url=foo.dev-${{ inputs.site_id }}.pantheonsite.io
        fi
        if [ "${{ inputs.type }}" == 'subdir' ]; then
          stdbuf -oL -eL terminus wp ${{ inputs.site_id }}.dev -- plugin activate wp-graphql --url=${{ inputs.site_url }}/foo
        fi

    - name: Run Playwright Tests on WordPress main site
      shell: bash
      env:
        SITE_NAME: ${{ inputs.site_name }}
        SITE_URL: ${{ inputs.site_url }}
      run: |
        echo ""
        echo -e "${{ env.BLUE }}Running Playwright tests${{ env.RESET }}"
        stdbuf -oL -eL npm run test .github/tests/wpcm.spec.ts

    - name: Run Playwright Tests on WordPress subdomain subsite
      if: ${{ inputs.type == 'subdom' }}
      env:
        SITE_NAME: ${{ inputs.site_name }}
        SITE_URL: https://foo.dev-${{ inputs.site_id }}.pantheonsite.io
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.BLUE }}Running Playwright tests on WordPress subdomain subsite${{ env.RESET }}"
        stdbuf -oL -eL npm run test .github/tests/wpcm.spec.ts

    - name: Run Playwright tests on WordPress subdirectory subsite
      if: ${{ inputs.type == 'subdir' }}
      env:
        SITE_NAME: ${{ inputs.site_name }}
        SITE_URL: ${{ inputs.site_url }}/foo
      shell: bash
      run: |
        echo ""
        echo -e "${{ env.BLUE }}Running Playwright tests on WordPress subdirectory subsite${{ env.RESET }}"
        stdbuf -oL -eL npm run test .github/tests/wpcm.spec.ts

    - name: Delete Site
      # Don't delete the subdomain multisite because those can't be free sites.
      if: success() && ${{ inputs.type != 'subdom' }}
      shell: bash
      run: |
        echo -e "${{ env.RED }}Deleting ${{ inputs.site_id }}${{ env.RESET }}"
        stdbuf -oL -eL terminus site:delete ${{ inputs.site_id }} -y
