name: Sync default to main
on:
  push:
    branches:
      - 'default'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync default branch to main
        run: |
          git config user.name "Pantheon Automation"
          git config user.email "bot@getpantheon.com"
          git checkout main
          git merge --no-edit origin/default
          git push origin main
